sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t walkermj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true walkermj/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-951344299841"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



